USE [master]
GO

/****** Object:  Database [personel]    Script Date: 1/18/2022 4:52:50 PM ******/
CREATE DATABASE [personel]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'personel', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\personel.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'personel_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\personel_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [personel].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [personel] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [personel] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [personel] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [personel] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [personel] SET ARITHABORT OFF 
GO

ALTER DATABASE [personel] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [personel] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [personel] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [personel] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [personel] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [personel] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [personel] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [personel] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [personel] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [personel] SET  DISABLE_BROKER 
GO

ALTER DATABASE [personel] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [personel] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [personel] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [personel] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [personel] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [personel] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [personel] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [personel] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [personel] SET  MULTI_USER 
GO

ALTER DATABASE [personel] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [personel] SET DB_CHAINING OFF 
GO

ALTER DATABASE [personel] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [personel] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [personel] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [personel] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [personel] SET QUERY_STORE = OFF
GO

ALTER DATABASE [personel] SET  READ_WRITE 
GO

